export const FETCH_HEADLINES = 'FETCH_HEADLINES'
export const FETCH_HEADLINES_SUCCESS = 'FETCH_HEADLINES_SUCCESS'
export const FETCH_HEADLINES_FAIL = 'FETCH_HEADLINES_FAIL'

export const FETCH_SOURCES = 'FETCH_SOURCES'
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS'
export const FETCH_SOURCES_FAIL = 'FETCH_SOURCES_FAIL'

export const SET_FILTER_COUNTRY = 'SET_FILTER_COUNTRY'
export const SET_FILTER_SOURCE_VIA_SEARCH = 'SET_FILTER_SOURCE_VIA_SEARCH'
export const SET_FILTER_SOURCE_VIA_PINNED = 'SET_FILTER_SOURCE_VIA_PINNED'


export const TOGGLE_PUSH_NOTIFS = 'TOGGLE_PUSH_NOTIFS'
export const TOGGLE_TIMELINE = 'TOGGLE_TIMELINE'